# outdir: passed by copr telling where to save the src.rpm
# spec: passed by copr telling which spec file should be used;
#       using for selecting the right src.rpm to be copied.

installdeps:
	dnf -y install coreutils curl dnf-utils findutils git java-11-openjdk-devel make maven rpmdevtools sed

srpm: installdeps
	.automation/build-srpm.sh
	find . -name '*.src.rpm' -exec cp {} $(outdir) \;
